# Generated by Django 3.2.8 on 2021-10-24 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maintenance', '0005_auto_20211024_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='detect_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 13, 37, 10, 418598)),
        ),
        migrations.AlterField(
            model_name='fault',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 13, 37, 10, 418598)),
        ),
        migrations.AlterField(
            model_name='faultcode',
            name='solution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
