# Generated by Django 3.2.8 on 2021-10-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maintenance', '0006_auto_20211024_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='detect_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 13, 49, 56, 315930)),
        ),
        migrations.AlterField(
            model_name='fault',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 13, 49, 56, 315930)),
        ),
        migrations.AlterField(
            model_name='faultcode',
            name='code',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
    ]
