# Generated by Django 3.2.8 on 2021-10-24 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maintenance', '0007_auto_20211024_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='detect_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 37, 16, 818895)),
        ),
        migrations.AlterField(
            model_name='fault',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 37, 16, 818895)),
        ),
        migrations.AlterField(
            model_name='faultcode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='faultcode',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
