# Generated by Django 3.2.8 on 2021-11-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maintenance', '0030_auto_20211101_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='detect_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 34, 16, 824779)),
        ),
        migrations.AlterField(
            model_name='fault',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 34, 16, 824779)),
        ),
    ]
