# Generated by Django 3.2.8 on 2021-11-01 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_maintenance', '0032_auto_20211101_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='detect_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 21, 23, 18, 79814)),
        ),
        migrations.AlterField(
            model_name='fault',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 21, 23, 18, 79814)),
        ),
    ]
