# Generated by Django 3.2.8 on 2021-10-23 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_machine', '0002_pallet'),
        ('app_production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='station',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_process', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 18, 29, 57, 397518))),
                ('end_process', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 18, 29, 57, 397518))),
                ('operator', models.IntegerField(blank=True, null=True)),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_machine.pallet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_production.product')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_machine.station')),
            ],
        ),
    ]
