# Generated by Django 3.2.8 on 2021-10-23 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0003_auto_20211023_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isNOK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isOK',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 5, 15, 790868)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 5, 15, 790868)),
        ),
    ]
