# Generated by Django 3.2.8 on 2021-10-23 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0005_auto_20211023_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 16, 28, 857941)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 16, 28, 857941)),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('-', '---'), ('OK', 'Part OK'), ('NOK', 'Part NOK')], default='-', max_length=3),
        ),
    ]
