# Generated by Django 3.2.8 on 2021-10-23 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0007_auto_20211023_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reference',
        ),
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 32, 9, 648210)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 19, 32, 9, 648210)),
        ),
    ]
