# Generated by Django 3.2.8 on 2021-10-23 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0013_auto_20211023_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('0', '---'), ('1', 'Pominięto'), ('2', 'OK'), ('3', 'NOK')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 20, 43, 8, 588309)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 20, 43, 8, 588309)),
        ),
    ]
