# Generated by Django 3.2.8 on 2021-10-23 22:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0016_auto_20211023_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 8, 25, 12817)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 8, 25, 12817)),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('0', '---'), ('1', 'POMINIĘCIE'), ('2', 'OK'), ('3', 'NOK')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='ProductDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_production.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_production.product')),
            ],
        ),
    ]
