# Generated by Django 3.2.8 on 2021-10-23 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0017_auto_20211024_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdatafield',
            old_name='name',
            new_name='process',
        ),
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 11, 18, 427261)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 11, 18, 427261)),
        ),
    ]
