# Generated by Django 3.2.8 on 2021-10-23 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0019_auto_20211024_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 28, 48, 707501)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 28, 48, 707501)),
        ),
        migrations.DeleteModel(
            name='ProductDataField',
        ),
        migrations.AddField(
            model_name='processdatafield',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_production.process'),
        ),
    ]
