# Generated by Django 3.2.8 on 2021-10-25 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0032_auto_20211024_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 4, 8, 184573)),
        ),
        migrations.AlterField(
            model_name='process',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='app_production.product'),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 4, 8, 184573)),
        ),
    ]
