# Generated by Django 3.2.8 on 2021-10-25 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0033_auto_20211025_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 9, 43, 268202)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 9, 43, 268202)),
        ),
        migrations.AlterField(
            model_name='processdatafield',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proc', to='app_production.process'),
        ),
    ]
