# Generated by Django 3.2.8 on 2021-10-25 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_machine', '0035_alter_pallet_register_date'),
        ('app_production', '0034_auto_20211025_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processdatafield',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processdatafield',
            name='value',
        ),
        migrations.AddField(
            model_name='processdatafield',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st', to='app_machine.station'),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 27, 4, 239497)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 27, 4, 239497)),
        ),
        migrations.CreateModel(
            name='ProcessDataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field', to='app_production.processdatafield')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proc', to='app_production.process')),
            ],
        ),
    ]
