# Generated by Django 3.2.8 on 2021-10-29 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0040_auto_20211029_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 15, 27, 32, 156442)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 15, 27, 32, 156442)),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('0', '---'), ('1', 'POMINIĘCIE'), ('2', 'OK'), ('3', 'NOK'), ('4', 'ANULOWANO')], default='0', max_length=1),
        ),
    ]
