# Generated by Django 3.2.8 on 2021-10-29 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0041_auto_20211029_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 15, 28, 28, 52467)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 15, 28, 28, 52467)),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('0', '---'), ('1', 'POMIŃ'), ('2', 'OK'), ('3', 'NOK'), ('4', 'ANULUJ')], default='0', max_length=1),
        ),
    ]
