# Generated by Django 3.2.8 on 2021-11-01 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_production', '0045_auto_20211030_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 10, 53, 43, 159503)),
        ),
        migrations.AddField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 10, 53, 43, 159503)),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 10, 53, 43, 159503)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 10, 53, 43, 159503)),
        ),
    ]
