# Generated by Django 3.2.8 on 2021-11-01 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_machine', '0053_alter_pallet_register_date'),
        ('app_production', '0052_auto_20211101_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 21, 23, 18, 79814)),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_process',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 21, 23, 18, 79814)),
        ),
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 21, 23, 18, 79814)),
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 21, 23, 18, 79814)),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/parts/jpg/')),
                ('status', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cam', to='app_machine.camera')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proces', to='app_production.process')),
            ],
        ),
    ]
