# Generated by Django 3.2.8 on 2021-10-23 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('type', models.IntegerField(default=0)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 18, 29, 57, 397518))),
                ('number_of_cycle', models.BigIntegerField(default=0)),
                ('cycle_limit', models.IntegerField(default=1000)),
                ('defect_limit', models.IntegerField(default=100)),
            ],
        ),
    ]
