# Generated by Django 3.2.8 on 2021-10-23 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_machine', '0002_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='type',
            field=models.CharField(choices=[('M', 'Manual process'), ('A', 'Auto process'), ('SA', 'Semi-auto process')], default='SA', max_length=2),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 18, 53, 8, 467688)),
        ),
    ]
